backend:
  name: github
  repo: naokomura/netlify-blog
  # branch: Setting by cms.js

media_folder: co6ei-note/src/images/upload
public_folder: /

publish_mode: editorial_workflow

display_url: https://sixaxd.com

collections:
  - name: 'blog'
    label: 'Blog'
    # folder: Setting by cms.js
    create: true
    preview_path_date_field: 'updated_on'
    slug: '{{year}}{{month}}{{day}}{{second}}{{minute}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
          default: null,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
          default: null,
        }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          multiple: true,
          options: ['Design', 'Development', 'Music', 'Other'],
          default: ['Other'],
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Featured Post',
          name: 'pickup',
          widget: 'boolean',
          required: false,
          default: false,
        }
